name: gala_business
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dio: ^5.9.0
  gap: ^3.0.1
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  video_player: ^2.10.0
  intl: ^0.20.2
  logger: ^2.6.2
  get_it: ^8.2.0
  keyboard_dismisser: ^3.0.0
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/home/
    - assets/icons/profil/
    - assets/icons/profil/vet_order/
    - assets/icons/filter/
